version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80" # Le frontend sera accessible sur http://localhost:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app:rw # Rechargement automatique en dev
      - /app/node_modules
    depends_on:
      - database

volumes:
  postgres_data:
