version: "3"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80" # Le frontend sera accessible sur http://localhost:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000" # Le backend sera accessible sur http://localhost:5000
    volumes:
      - ./server:/app:rw # Rechargement automatique en dev
      - /app/node_modules # Ignorer les node_modules